# Generated by Django 3.1.4 on 2021-01-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.item'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PET', 'Petit'), ('MOY', 'Moyen'), ('GRA', 'Grand')], max_length=5)),
                ('price', models.FloatField()),
                ('poids', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('liked', models.IntegerField(default=0)),
                ('cat', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
                ('items', models.ManyToManyField(to='mainApp.Item')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.panier'),
        ),
    ]
