# Generated by Django 3.1.4 on 2021-01-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='cat',
        ),
        migrations.AddField(
            model_name='panier',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
