# Generated by Django 3.1.4 on 2021-01-03 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20210103_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.panier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.item'),
        ),
    ]
